### ISSUE TITLE
Using a dependency with scope 'import' and type 'pom' prevents gradle builds from compiling

### ISSUE THREAD

**Issue by jblack10101** [arquillian/arquillian-container-osgi#14]
I'm trying to compile the latest version of arquillian-container-felix-embedded in gradle with:
```
compile 'org.jboss.arquillian.container:arquillian-container-felix-embedded:2.1.0.CR15'
```

But in the jar execution phase, I get message:
```
Could not copy MANIFEST.MF to 'C:\workspace-ggts\arquillian\build\tmp\jar\MANIFEST.MF'.
> java.util.zip.ZipException: The JAR/ZIP file (C:\Users\904783\.gradle\caches\modules-2\files-2.1\org.jboss.shrinkwrap.resolver\shrinkwrap-resolver-depchain\2.0.0\dfa4e3db4c9752371b1873a728bb0fffd58437f7\shrinkwrap-resolver-depchain-2.0.0.pom) seems corrupted,
 error: error in opening zip file
```

Because the latest version of arquillian-container-osgi depends on a pom file, like this:

```
<dependency>
    <groupId>org.jboss.arquillian</groupId>
    <artifactId>arquillian-bom</artifactId>
    <version>${version.jboss.arquillian.core}</version>
    <scope>import</scope>
    <type>pom</type>
</dependency>
```

And Gradle tries to treat the pom like a jar/zip file.

It would be nice if pom dependency imports like this were handled in a different way, so these jars can be included in gradle builds.  As it is now, only maven is supported for building anything that uses this jar.

**Comment by tdiesler** [comment]
Out of date - please use [Jira](https://issues.jboss.org/browse/ARQ)
