### ISSUE TITLE
allow deploying features files to remote / managed karaf containers

### ISSUE THREAD

**Issue by christian-posta** [arquillian/arquillian-container-osgi#41]

**Comment by tdiesler** [comment]
Please move this to https://issues.jboss.org/browse/ARQ

**Comment by christian-posta** [comment]
can track there (jira), that's fine... can i submit PR for this on github? or attach patch to the jira? what's the process for this?

**Comment by tdiesler** [comment]
PR to this repo would be awesome - thanks Christian
